--USERS
INSERT INTO USER (FIRSTNAME, LASTNAME, USERNAME, EMAIL, PASSWORD) VALUES ('Pedro', 'Perez', 'user', 'mail@mail.com','password');
INSERT INTO USER (FIRSTNAME, LASTNAME, USERNAME, EMAIL, PASSWORD) VALUES ('Maria', 'Martinez', 'admin', 'mimail@gmail.com','password');
INSERT INTO USER (FIRSTNAME, LASTNAME, USERNAME, EMAIL, PASSWORD) VALUES ('javier', 'Lozano', 'test1@outlook.com', 'otromail@hotmail.com.ar','12345');
INSERT INTO USER (FIRSTNAME, LASTNAME, USERNAME, EMAIL, PASSWORD) VALUES ('Dora', 'Carllen', 'test2@outlook.com', 'masmail@yahoo.com.ar','12345');

--AUTHORITIES
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('user','ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('admin','ROLE_ADMIN');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('test1@outlook','ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('test2@outlook','ROLE_USER');

